#!/usr/bin/env python3
"""
Seed Data: Master Configuration
===============================
1. Maps Apple/Tech specific terms to CORE US GAAP tags (Safe Mode).
2. Maps Generic terms (Revenue, Assets) for robustness.
"""
import csv
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALIAS_PATH = os.path.join(BASE_DIR, "config", "aliases.csv")

# Format: (Source_Label, Target_Element_ID, Taxonomy)
REAL_WORLD_DATA = [
    # --- 1. APPLE / TECH SPECIFICS (Mapped to Core Tags) ---
    ("Products net sales", "us-gaap_Revenues", "US_GAAP"),
    ("Services net sales", "us-gaap_Revenues", "US_GAAP"),
    ("Total net sales", "us-gaap_Revenues", "US_GAAP"),
    ("Net sales", "us-gaap_Revenues", "US_GAAP"),
    
    # Cost & Opex
    ("Total cost of sales", "us-gaap_CostOfRevenue", "US_GAAP"),
    ("Cost of sales", "us-gaap_CostOfRevenue", "US_GAAP"),
    ("Research and development", "us-gaap_ResearchAndDevelopmentExpense", "US_GAAP"),
    ("Selling, general and administrative", "us-gaap_SellingGeneralAndAdministrativeExpense", "US_GAAP"),
    ("Total operating expenses", "us-gaap_OperatingExpenses", "US_GAAP"),
    ("Operating income", "us-gaap_OperatingIncomeLoss", "US_GAAP"),
    
    # Income & Tax
    ("Income before income taxes", "us-gaap_IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest", "US_GAAP"),
    ("Provision for income taxes", "us-gaap_IncomeTaxExpenseBenefit", "US_GAAP"),
    ("Net income", "us-gaap_NetIncomeLoss", "US_GAAP"),
    
    # Balance Sheet Assets
    ("Cash and cash equivalents", "us-gaap_CashAndCashEquivalentsAtCarryingValue", "US_GAAP"), # Force US GAAP
    ("Marketable securities (current)", "us-gaap_MarketableSecuritiesCurrent", "US_GAAP"),
    ("Vendor non-trade receivables", "us-gaap_NontradeReceivablesCurrent", "US_GAAP"),
    ("Total current assets", "us-gaap_AssetsCurrent", "US_GAAP"),
    ("Total non-current assets", "us-gaap_AssetsNoncurrent", "US_GAAP"),
    ("Total assets", "us-gaap_Assets", "US_GAAP"),
    
    # Balance Sheet Liabs
    ("Commercial paper", "us-gaap_CommercialPaper", "US_GAAP"),
    ("Term debt", "us-gaap_LongTermDebt", "US_GAAP"),
    ("Total current liabilities", "us-gaap_LiabilitiesCurrent", "US_GAAP"),
    ("Total non-current liabilities", "us-gaap_LiabilitiesNoncurrent", "US_GAAP"),
    ("Total liabilities", "us-gaap_Liabilities", "US_GAAP"),
    ("Total shareholders' equity", "us-gaap_StockholdersEquity", "US_GAAP"),
    
    # Cash Flow
    ("Cash generated by operating activities", "us-gaap_NetCashProvidedByUsedInOperatingActivities", "US_GAAP"),
    ("Cash generated by investing activities", "us-gaap_NetCashProvidedByUsedInInvestingActivities", "US_GAAP"),
    ("Cash used in financing activities", "us-gaap_NetCashProvidedByUsedInFinancingActivities", "US_GAAP"),
    ("Increase / (Decrease) in cash", "us-gaap_CashAndCashEquivalentsPeriodIncreaseDecrease", "US_GAAP"),
    ("Ending cash balance", "us-gaap_CashAndCashEquivalentsAtCarryingValue", "US_GAAP"),

    # --- 2. GENERIC FALLBACKS ---
    ("Revenue", "us-gaap_Revenues", "US_GAAP"),
    ("Total Revenue", "us-gaap_Revenues", "US_GAAP"),
    ("Cost of Sales", "us-gaap_CostOfRevenue", "US_GAAP"),
    ("Gross Margin", "us-gaap_GrossProfit", "US_GAAP"),
    ("Opex", "us-gaap_OperatingExpenses", "US_GAAP"),
    ("Assets", "us-gaap_Assets", "US_GAAP"),
    ("Liabilities", "us-gaap_Liabilities", "US_GAAP"),
    ("Equity", "us-gaap_StockholdersEquity", "US_GAAP")
]

def populate():
    print(f"Generating clean aliases.csv with {len(REAL_WORLD_DATA)} entries...")
    with open(ALIAS_PATH, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["source","alias","element_id"])
        
        # Write unique entries only
        seen = set()
        count = 0
        for lbl, eid, src in REAL_WORLD_DATA:
            key = lbl.lower()
            if key not in seen:
                writer.writerow([src, lbl, eid])
                seen.add(key)
                count += 1
    print(f"Success. Wrote {count} aliases.")

if __name__ == "__main__":
    populate()